### ISSUE TITLE
Nuget package requiring net 8.0

### ISSUE THREAD

**Issue by Yazir** [Pieeer1/SteamMultiplayerPeer#11]
Awesome work, saves me a lot of headache

I noticed that nuget package requires net 8.0, I'm questioning whether that's necessary. I myself upgraded to 8.x, but I see no reason for the minimum .net to be that version.

https://www.nuget.org/packages/SteamMultiplayerPeer/1.0.4

The issue can be ignored as as of now Godot C# configuration requires net8.0, so we might disregard it and just hold it as the standard.

**Comment by Pieeer1** [comment]
I currently use some collection expressions which are a new .net 8 feature, however yes, most of the functionality works on .Net 6 as well. Theoretically we could go back and remove them for compatibility purposes, but since Godot supports .NET 8 fully, I focused on the newer LTS version.

**Comment by Pieeer1** [comment]
closing due to not supporting lower than .net 8
